### ISSUE TITLE
Invalid time stamp on iOS devices

### ISSUE THREAD

**Issue by Me-sudoer** [make-all/metlink-nz#2]
When using the integration on both the companion app in or browser (Safari/Edge Chromium) on iOS 14.6 device - the entities card displays 'Invalid Timestamp' for each stop that is monitored.

The integration runs fine on Android.

**Comment by make-all** [comment]
It seems like the issue described here: https://community.home-assistant.io/t/timestamp-cant-show-in-ios-app-but-working-on-chrome/102714/3

The departure attribute has the correct format, so a workaround might be to display that instead of the state.  But later comments on that issue suggest that the missing T is not the actual cause, so it maybe won't be a workaround.  The state is passed to HomeAssistant as a datetime object, so any formatting is up to Home Assistant itself.  The departure attribute is a string directly from the Metlink API.

**Comment by make-all** [comment]
Please try version 1.0.2.  To avoid waiting the few hours it takes HACS to notice an update, you can click on the menu button on the Metlink entry in HACS, and choose "Update Information".

**Comment by Me-sudoer** [comment]
Legend. Thanks Jason.
